### ISSUE TITLE
DKI microstructure model tests still fail intermittenly

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1242] opened 2017-05-14 04:00 UTC
This seems to be a failure in predicting from the model: https://travis-ci.org/nipy/dipy/jobs/231992444, but it might just be a numerical precision issue.

**Comment by RafaelNH** [comment] 2017-05-14 08:46
Yup should only be a numerical precision issue! I didn't spot this before cause I am not able to reproduce this intermit fail in my local PC! I create a PR to address this:

PR #1244

**Comment by skoudoro** [comment] 2017-06-20 17:01
Should we close this issue @arokem @RafaelNH ?

**Closed** 2017-06-20 17:24 UTC
