### ISSUE TITLE
Median_otsu b0slices too implicit?

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#238] opened 2013-09-03 17:28 UTC
I find the API for `median_otsu` a bit scary - because it assumes that the (only) b0 volume in a 4D image is the first.

I think this is too implicit as in zen-of-python:

"explicit is better than implicit"

I think it would be too easy for someone to use this blindly without realizing which volume(s) they were selecting.  Also it implies that elsewhere in dipy we expect the b0 to be at 0 which presumably is not the case?

Ideas I can think of:
- move `b0slice` argument to be before `autocrop`, and allow None only if `input_volume` is a 3D  array (raise Error otherwise).
- Remove `b0slice` argument and make the user generate the 3D image for `median_otsu` to work on.

**Comment by skoudoro** [comment] 2017-06-15 18:36
![](https://github.trello.services/images/mini-trello-icon.png) [#238](https://trello.com/c/VVh0w4rv/1-238)

**Comment by skoudoro** [comment] 2019-04-30 16:09
Is it still an issue @arokem @matthew-brett? Can I close it?

It is a quite old issue and it seems that `b0slice` has been replaced by `vol_idx` as you can see (here)[https://github.com/nipy/dipy/blob/master/dipy/segment/mask.py#L123]. This variable allows to select many volumes on our 4D data and take the means of this selection.

**Comment by arokem** [comment] 2019-05-03 20:23
The problem is that the [default behavior](https://github.com/nipy/dipy/blob/master/dipy/segment/mask.py#L197) is still implicitly still making some rather scary assumptions

**Comment by skoudoro** [comment] 2019-05-09 13:36
fixed by #1821, closing

**Closed by skoudoro** 2019-05-09 13:36 UTC
Labels: state: needs PR, type:Enhancement
