### ISSUE TITLE
Dependency Graph: Dependents?

### ISSUE THREAD

**Issue by ShreyasFadnavis** [nipy/dipy#1860] opened 2019-06-19 02:44 UTC
Hi,

I wonder why we can't see the other packages/ repos that depend on DIPY in the dependency graph: https://github.com/nipy/dipy/network/dependents

It would be nice to have a `Used By` for the project. There should be something that we need to fix maybe?

**Comment by arokem** [comment] 2019-06-19 02:54
This is a duplicate of #1856.

**Closed by arokem** 2019-06-19 02:54 UTC
Labels: :speech_balloon:type:Discussion :speech_balloon:
