### ISSUE TITLE
Actual S0 for DTI data

### ISSUE THREAD

**Issue by etpeterson** [nipy/dipy#1148] opened 2016-11-11 19:16 UTC
Hey @arokem didn't you have some code to calculate the actual b=0 intercept from the DTI fit? Did that make it into the repo somewhere? I want to compare IVIM and DTI fits but I need the actual intercept for the DTI fit.

**Comment by arokem** [comment] 2016-11-11 22:12
It's in this unmerged PR:https://github.com/nipy/dipy/pull/1036 

We decided not to merge it, because it would incur a performance regression. It occurs to me that we might still want to integrate that into our code base, even if we don't require it be used in every case that DTI is fit.

**Comment by etpeterson** [comment] 2016-11-11 23:43
Thanks, that explains why I couldn't find it.

For context I was going to try to fit the DTI and IVIM models and then compare them to see which regions has a better quality fit, and I also wanted to implement a faster double linear IVIM fit using the DTI routines. But in both cases I need the S0 value. I ended up using polyfit like the IVIM code does but I think it makes sense to leverage the DTI implementation in those cases. Is there any reason to use polyfit over DTI other than it just doesn't return the S0 value?

**Comment by arokem** [comment] 2016-12-01 03:00
Sorry for the slowness here. I am not sure that I understand that last sentence. Can you paraphrase?

**Comment by etpeterson** [comment] 2016-12-01 16:57
Basically I'm wondering about the advantages or disadvantages of using the DTI fit compared with polyfit. I'm leaning towards DTI because it already has a lot of options but if it's to slow or if the S0 isn't going to be included then maybe polyfit is the better choice. Do you have thoughts/comments on the plusses or minuses for either method?

**Comment by arokem** [comment] 2016-12-05 03:41
DTI is going to be rather fast, compared to doing polyfit in every voxel, because you can fit it in one fell swoop for your entire volume. You can infer S0 either from the fit, or (as we do in our prediction) from the measured S0 volumes (assuming you have measured S0).

**Comment by RafaelNH** [comment] 2016-12-05 12:36
well, for @etpeterson's mentioned aim, you need to infer S0 from the DTI's fit.

Some months ago I had a meeting with @arokem and @Garyfallidis to discuss how to incorporate the S0 fit in DTI's fit class instance. My first suggestion was to add S0 as a model parameter (e.g. adding it as the last element of model_params). However, since this small change will mess with all other Dipy models that depend on DTI, we explored other alternatives such as estimating S0 after the parameters fit (suggestions at [https://gist.github.com/arokem/508dc1b22bdbd0bdd748](https://gist.github.com/arokem/508dc1b22bdbd0bdd748)).

Although we decided not to carry with these changes directly into the class fit instance (since it was reducing speed performance), you can infer S0 from DTI posteriorly from DTI model_params and the data using the mathematical proof and code at [https://gist.github.com/arokem/508dc1b22bdbd0bdd748](https://gist.github.com/arokem/508dc1b22bdbd0bdd748).

**Comment by etpeterson** [comment] 2016-12-05 19:57
Thanks guys. I think I'd like to use DTI but I do need the S0 from the fit so it looks like I'm bringing this up again.

I see S0 is calculated in at least OLS and WLS but discarded so maybe a flag to save it? I'm guessing you already thought of this, but maybe as an optional input to TensorFit?

**Comment by arokem** [comment] 2016-12-06 05:51
I'd support that, assuming there is no performance cost to doing that.

You can see how I did it in that closed PR - that was too costly. If you
can find another way, that would be great.

**Comment by etpeterson** [comment] 2016-12-06 17:37
OK, sounds good to me. I'll explore a little and see if what I'm envisioning is possible.

**Comment by sahmed95** [comment] 2016-12-07 00:15
Talking about measuring performance change over time, I recently came across [airspeed](http://conference.scipy.org/scipy2014/schedule/presentation/1693/) - a tool for benchmarking Python software projects over their lifetime. From the Scipy talk : 

>> As software projects mature and become more robust against bugs, they may also lose some of their runtime performance and memory efficiency. Airspeed velocity (asv) is a new tool to help find those performance degradations before they get out to end users. It automatically runs a benchmark suite over a range of commits in a project's repository, as well as in a matrix of configurations of Python versions and other dependencies. The results, possibly from multiple machines, are then collated and published in a web-based report.

@arokem Is this something that can be helpful while tracking performance regression ? I can open a new issue if this seems to be something we would like to do in future.

**Comment by etpeterson** [comment] 2016-12-07 21:53
Alright, I've had a productive few days and managed to get this together: https://github.com/etpeterson/dipy

It seems like it's working and the speed is similar, only increasing by 50ms for a total fit time around 3s but the size does increase from about 1.56GB to 1.7GB. But that's just with the option turned off vs turned on whereas the real test is vs master as well.

I still need to add more tests, documentation, and come up with a better speed and memory comparison. I also have IVIM edits in there as well, so I should strip those out for a PR.

Of course I'm happy to hear thoughts about this.

**Comment by arokem** [comment] 2016-12-07 22:09
Sounds promising! A PR would be helpful, so that we can see what's changed.

**Comment by RafaelNH** [comment] 2016-12-08 11:17
Yes, please do a PR (or two PRs - one for DTI and another for IVIM)! Would love to review it!

**Comment by arokem** [comment] 2016-12-16 20:45
I guess I can close this one. Please reopen if this still needs to be here.

**Closed by arokem** 2016-12-16 20:45 UTC
