### ISSUE TITLE
Importing vtk with dipy

### ISSUE THREAD

**Issue by vibhatha** [nipy/dipy#1170] opened 2017-01-21 16:34 UTC
I tried to execute the code in the following link.
https://github.com/nipy/dipy/blob/master/doc/examples/viz_surfaces.py

But I got the following error, when I was importing the packages.

I used pip to install all the requirements and I am working with Python 2.7.12 with Anaconda2. 

Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import dipy
>>> import dipy.io
>>> import dipy.io.vtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named vtk

**Comment by arokem** [comment] 2017-01-21 17:02
`conda install vtk`

should do it

**Comment by vibhatha** [comment] 2017-01-21 17:03
I already did it. I am having this issue, when importing. I even updated
it.

With Regards,
Vibhatha Abeykoon

**Comment by MarcCote** [comment] 2017-01-21 17:23
If in a Python console `import vtk` doesn't work that would suggest the problem is related to your conda installation.

**Comment by vibhatha** [comment] 2017-01-21 17:23
import vtk works.

With Regards,
Vibhatha Abeykoon

**Comment by Garyfallidis** [comment] 2017-01-21 17:27
What is likely happening is that our setup.py is not updated with the new module dipy.io.vtk

**Comment by vibhatha** [comment] 2017-01-21 17:28
Okay I understand it. How should we work on that ?

With Regards,
Vibhatha Abeykoon

**Comment by Garyfallidis** [comment] 2017-01-21 17:31
No, what I said is wrong. That would be the case if io.vtk was a folder. 
You have multiple conflicting installations of DIPY @vibhatha 
Write 
```
import dipy
dipy.__version__
dipy.__file___
```
and tell us what you get.

**Comment by vibhatha** [comment] 2017-01-21 17:33
dipy.__version__
'0.11.0'
>>> dipy.__file__
'C:\\Users\\vibha\\Anaconda2\\lib\\site-packages\\dipy\\__init__.pyc'

With Regards,
Vibhatha Abeykoon

**Comment by Garyfallidis** [comment] 2017-01-21 17:42
Yeah, you are using the release version. 
This module (dipy.io.vtk) was added in the development version.
```
pip uninstall dipy
```
And then install the development version.
```
get the zip https://github.com/nipy/dipy/archive/master.zip
cd dipy (go to folder where the setup.py is0
pip install -e .
```

**Comment by vibhatha** [comment] 2017-01-21 17:43
I will do this :)
Thanks a lot for helping me out.

With Regards,
Vibhatha Abeykoon

**Comment by Garyfallidis** [comment] 2017-01-21 17:43
No problem @vibhatha!
Thanks for asking!

**Comment by vibhatha** [comment] 2017-01-21 17:44
Thanks again

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment] 2017-01-23 01:56
I tried to run the code, after re-installing everything, but I am getting
the following error.

runfile('C:/Users/vibha/OneDrive/Documents/ISE/Semester 2/Image Processing
and Machine Learning/Assignments/Assignment 1/cube_plot.py',
wdir='C:/Users/vibha/OneDrive/Documents/ISE/Semester 2/Image Processing and
Machine Learning/Assignments/Assignment 1')
Traceback (most recent call last):

  File "<ipython-input-4-8cea158f4ac2>", line 1, in <module>
    runfile('C:/Users/vibha/OneDrive/Documents/ISE/Semester 2/Image
Processing and Machine Learning/Assignments/Assignment 1/cube_plot.py',
wdir='C:/Users/vibha/OneDrive/Documents/ISE/Semester 2/Image Processing and
Machine Learning/Assignments/Assignment 1')

  File
"C:\Users\vibha\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py",
line 866, in runfile
    execfile(filename, namespace)

  File
"C:\Users\vibha\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py",
line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/vibha/OneDrive/Documents/ISE/Semester 2/Image Processing
and Machine Learning/Assignments/Assignment 1/cube_plot.py", line 66, in
<module>
    ut_vtk.set_polydata_triangles(my_polydata, my_triangles)

  File "C:\Users\vibha\Anaconda2\lib\site-packages\dipy\viz\utils.py", line
348, in set_polydata_triangles
    vtk_triangles = ns.numpy_to_vtkIdTypeArray(vtk_triangles, deep=True)

  File
"C:\Users\vibha\Anaconda2\lib\site-packages\vtk\util\numpy_support.py",
line 191, in numpy_to_vtkIdTypeArray
    'Expecting a numpy.int64 array, got %s instead.' % (str(dtype))

ValueError: Expecting a numpy.int64 array, got int32 instead.



And then I changed the array type to the expected type, then the python
kernel freezes and stop responding.
Is there any new version of this code or am I doing something wrong here.

With Regards,
Vibhatha Abeykoon

**Comment by arokem** [comment] 2017-03-29 15:26
Should have been resolved here: https://github.com/nipy/dipy/pull/1171

Closing for now, but let us know if this is still an issue

**Closed by arokem** 2017-03-29 15:26 UTC

**Comment by vibhatha** [comment] 2017-03-29 16:46
Okay, Thank you very much.

With Regards,
Vibhatha Abeykoon
