### ISSUE TITLE
Use absolute instead of relative import

### ISSUE THREAD

**Issue by samuelstjean** [nipy/dipy#969] opened 2016-03-13 20:29 UTC
For anyone wanting to fix quick stuff, turning all of the relative import to absolute import would be useful to prevent name clashes when importing files from other projects or locally from the working folder. Reverse issue from #968 funnily enough.

**Comment by arokem** [comment] 2016-03-13 20:30
:+1: 

Thanks!

**Comment by samuelstjean** [comment] 2016-03-13 20:35
Anyway, I am still surprised that nibabel only uses relative imports instead, why one versus the other? Absolut import are not always abolute, have your current ipython console in a folder with a file named diy, ti will pick this one up before the whole library, resulting in bugs in import and other missing stuff for example, and me wondering why do people have weirds bugs I do not have after that, but that is another story.

**Comment by matthew-brett** [comment] 2016-03-13 20:41
I don't think it's a big deal either way.

We're gradually moving away from relative imports in the tests, partly because we may be switching to pytests in the future, and you need absolute imports in tests to be able to run the tests in the working tree, while importing the code from the installed tree.  But, we're just doing that as we edit files for other reasons.

**Comment by samuelstjean** [comment] 2016-03-13 20:43
Damn, and here I told marc-alexandre to change his imports because of that in his tractogram stuff. They do prevent clashing with vanilla nibabel to test his stuff though and allows both to coexist.

**Comment by arokem** [comment] 2016-03-13 20:44
Whoops. Was just posting this: https://github.com/nipy/nibabel/issues/424

**Comment by souravsingh** [comment] 2016-03-14 13:14
I would like work on this issue

**Comment by jchoude** [comment] 2016-03-14 13:50
Just a quick comment, as it also relates to the original issue: I am also -1 on relative imports. Personal reason, apart from PEP8 suggestions and consensus, is that it often helps avoid bugs when refactoring and moving code. It also helps to see from which package a function (or class or anything) is imported. 

@samuelstjean That would also allievate your import problems, because it's then clear how to specify if you want to import a function from scilpy or dipy.

**Comment by Garyfallidis** [comment] 2016-03-14 14:18
@souravsingh be happy to work on this issue. You need to look to find modules that use relative imports and change them to absolute. For example,

https://github.com/nipy/dipy/blob/master/dipy/reconst/dki.py
https://github.com/nipy/dipy/blob/master/dipy/reconst/shore.py

**Comment by sahmed95** [comment] 2016-03-14 16:48
I have found over 157 matches across 73 files using a regex for relative imports which can be changed. Where do I post them ?

**Comment by arokem** [comment] 2016-03-14 16:50
Thanks for taking a look! Best to post them as several different issues, possibly divided by modules. That way, people can take these changes bit by bit. Easier to review that way.

**Comment by sahmed95** [comment] 2016-03-14 16:56
There will be a lot of issues then. Should I remove the last comment with the long list and perhaps make a text file and upload all the instances under this issue ?

**Comment by theaverageguy** [comment] 2016-03-21 12:10
Is this one done?

**Comment by theaverageguy** [comment] 2016-03-22 14:29
@arokem could you tell if I can fix this?

**Comment by arokem** [comment] 2016-03-22 14:38
Hi @theaverageguy - I love the enthusiasm! This one is not resolved everywhere -- there are still several places in the code that have relative imports. Feel free to change these into absolute imports, but please make only small PRs with these changes, so that it's easier to review, and please don't make changes to the cython code (in the .pyx files).

**Comment by sahmed95** [comment] 2016-03-22 17:57
@theaverageguy Hi, thanks for taking a look. I have opened all the other absolute import issues. Please have a look above. @arokem Is it necessary to change the __init__ files too? #995

**Comment by arokem** [comment] 2016-03-22 17:59
Please don't touch the `__init__` files!

**Comment by sahmed95** [comment] 2016-03-22 18:09
Sorry. I should have confirmed. I had a doubt about __init__. Updating now the issues to avoid __init__. Anything else to keep in mind. I guess this sorts out all the absolute import cases.

**Comment by skoudoro** [comment] 2017-06-15 18:50
![](https://github.trello.services/images/mini-trello-icon.png) [#969](https://trello.com/c/KgFUazjV/9-969)

**Comment by skoudoro** [comment] 2017-06-26 14:10
At the end, it seems to be fix ! All related issues are closed, any comment ? Should I close this one ?

**Comment by arokem** [comment] 2017-06-26 20:35
Yup. Let's close this.

**Closed by arokem** 2017-06-26 20:35 UTC
Labels: Beginner-friendly
