### ISSUE TITLE
No module named 'vtkCommonCore' 

### ISSUE THREAD

**Issue by andresdasugo** [nipy/dipy#1313] opened 2017-08-01 04:27 UTC
When I want to import vtk on Python (Windows 10) this error appears 

import vtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\VTK 6.3.0\bin\Lib\site-packages\vtk\__init__.py", line 39, in <module>
    from vtkCommonCore import *
  File "C:\Program Files\VTK 6.3.0\bin\Lib\site-packages\vtk\vtkCommonCore.py", line 1, in <module>
    from vtkCommonCorePython import *
ImportError: dynamic module does not define module export function (PyInit_vtkCommonCorePython)

I have already create the enviromental variables but this problem still occurs, if someone could help I would be very thankfull.

**Comment by skoudoro** [comment] 2017-08-01 13:19
Hi @andresdasugo , How did you install vtk ? what is the python version ? It looks like a vtk installation issue (a missing library or  init script / ). The second option is a mismatch between your python version and the one used to compiled vtk.

Yesterday, I installed successfully vtk and dipy on windows 10 with [anaconda](https://www.continuum.io/downloads). Maybe you should try this alternative :
```
conda install -c conda-forge dipy
conda install -c conda-forge vtk
```

**Comment by skoudoro** [comment] 2017-08-06 14:30
Did you resolve your problem @andresdasugo ? Can we close this issue ?

**Comment by skoudoro** [comment] 2017-08-14 02:32
closing. Feel free to reopen it if needed

**Closed by skoudoro** 2017-08-14 02:32 UTC

**Comment by CarinRae** [comment] 2019-11-26 14:38
Hi, I am now having the same issue:
---
   import vtk
  File "C:\Users\CarinETH\Anaconda3\envs\py2\lib\site-packages\vtk\__init__.py", line 41, in <module>
    from .vtkCommonCore import *
  File "C:\Users\CarinETH\Anaconda3\envs\py2\lib\site-packages\vtk\vtkCommonCore.py", line 9, in <module>
    from vtkCommonCorePython import *
ImportError: No module named vtkCommonCorePython
----------

I am using python 2.7.17 and vtk 7.0.0. The above solution isnt helping me. Any idea what the issue is? Thanks in advance!

**Comment by skoudoro** [comment] 2019-11-26 16:35
Hi @CarinRae,

Are you sure about your VTK version? look like you have a newer version of VTK. I think you have some conflict with your environment but not sure. 

`vtkCommonCorePython` should be in `C:\Users\CarinETH\Anaconda3\envs\py2\lib\site-packages\vtk\vtkCommonCorePython.pyd(or dll)` so if it is not present, this is an installation issue.  if it is present, this is a path environnment issue or conflict issue with another installation.

Can you check it via this command:
```

import vtk
print(vtk.vtkVersion.GetVTKSourceVersion())
```

**Comment by CarinRae** [comment] 2019-11-27 12:28
Hi, Thanks for your reply. I double checked the directory as you listed and the vtkCommonCorepython.pyd exists in (C:\Users\CarinETH\Anaconda3\envs\py2\Lib\site-packages\vtk). When I run "conda list" I also return that I have vtk 7.0.0.

But, when I start python (in the same environment) and run import vtk I get the same error as above:
 File "<stdin>", line 1, in <module>
  File "C:\Users\CarinETH\Anaconda3\envs\py2\lib\site-packages\vtk\__init__.py", line 41, in <module>
    from .vtkCommonCore import *
  File "C:\Users\CarinETH\Anaconda3\envs\py2\lib\site-packages\vtk\vtkCommonCore.py", line 9, in <module>
    from vtkCommonCorePython import *
ImportError: No module named vtkCommonCorePython


the other modules (ie matplotlib, numpy, etc ) work fine so its just vtk.

Still not sure whats going on

**Comment by ccz359** [comment] 2022-01-24 17:28
Hi @skoudoro ,

I am a new user to Python, and have downloaded version 3.9. I created an environment that uses 3.7 to install several modules that required that version. I think I have the problem you mentioned in your last comment on this thread, where I compiled VTK in 3.9 installed it successfully in 3.7, however I'm receiving the error when I run my code: 

  File "C:\Users\16035\.conda\envs\py37\lib\site-packages\vtkmodules\vtkCommonCore.py", line 9, in <module>
    from vtkCommonCorePython import *

ModuleNotFoundError: No module named 'vtkCommonCorePython'

When I go check that folder, the 'vtkCommonCorePython' is not present. How do I go about fixing this issue?

Many thanks!

**Comment by skoudoro** [comment] 2022-01-24 17:55
Hi @ccz359,

I am not sure I understand your environment. And especially this sentence: 
> where I compiled VTK in 3.9 installed it successfully in 3.7

Can you do 
```python
pip show vtk
pip list
```

ps: if you compile vtk for 3.9, it will only work for python 3.9 and nothing else. If need VTK for python 3.7, you should do `pip install vtk` or make sure that you compile it for python37

**Comment by ccz359** [comment] 2022-01-24 21:33
@skoudoro I uninstalled Python 3.9 and installed 3.7 instead, hoping to fix the problem, but that didn't work. The 'vtkCommonCorePython' file does show up now in the indicated folder. FYI I'm on a Windows 10, working in an ipython environment. Seems I have the same issue now as OP.

  File "C:\ProgramData\Anaconda3\lib\site-packages\vtkmodules\vtkCommonCore.py", line 9, in <module>
    from vtkCommonCorePython import *

ModuleNotFoundError: No module named 'vtkCommonCorePython'

pip show vtk returns:
pip show vtk
Name: vtk
Version: -PKG-VERSION
Summary: VTK is an open-source toolkit for 3D computer graphics, image processing, and visualization
Home-page: 
Author: 
Author-email: 
License: 
Location: c:\programdata\anaconda3\lib\site-packages
Requires: 
Required-by: meshmagick
Note: you may need to restart the kernel to use updated packages.

and pip list returns many items, the vtk line is:
vtk                                -PKG-VERSION

I've spent many days on this issue now. I appreciate any light you can shed!
